'use client';

import React from 'react';
import {
  FileText,
  Printer,
  X,
  QrCode,
  ShieldCheck,
  CheckCircle2,
  Building2,
  UserCheck,
  Tag,
  Clock,
  Sparkles
} from 'lucide-react';
import type { SupportedCurrency } from '@agent-sauda/domain';
import { formatCurrencyAmount } from '@agent-sauda/domain';

export interface InvoiceItem {
  id: string;
  productTitle: string;
  quantity: number;
  unitPrice: number;
  agreedPrice: number;
  subtotal: number;
}

export interface InvoiceData {
  documentType: 'PROFORMA_QUOTE' | 'TAX_INVOICE';
  documentNumber: string;
  date: string;
  validUntil?: string;
  merchantName: string;
  merchantGstin?: string;
  merchantAddress?: string;
  customerName: string;
  customerPhone?: string;
  customerEmail?: string;
  isCustomerVerified?: boolean;
  items: InvoiceItem[];
  subtotal: number;
  discountAmount: number;
  discountPercent: number;
  totalAmount: number;
  currency?: SupportedCurrency;
  status: string;
  paymentId?: string;
  cryptoHash?: string;
}

interface InvoiceModalProps {
  isOpen: boolean;
  onClose: () => void;
  data: InvoiceData;
}

export function InvoiceModal({ isOpen, onClose, data }: InvoiceModalProps) {
  if (!isOpen) return null;

  const currency = data.currency || 'INR';
  const isTaxInvoice = data.documentType === 'TAX_INVOICE';
  
  // 18% GST Breakdown (9% CGST + 9% SGST)
  const taxableValue = Number((data.totalAmount / 1.18).toFixed(2));
  const cgstAmount = Number(((data.totalAmount - taxableValue) / 2).toFixed(2));
  const sgstAmount = Number(((data.totalAmount - taxableValue) / 2).toFixed(2));
  
  const offerSha256 =
    data.cryptoHash ||
    `sauda_sha256_${data.documentNumber.replace(/[^a-zA-Z0-9]/g, '').toLowerCase()}_${Date.now().toString(16)}`;

  const handlePrint = () => {
    window.print();
  };

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/80 p-4 backdrop-blur-sm animate-in fade-in duration-200">
      <div className="relative w-full max-w-3xl max-h-[90vh] overflow-y-auto rounded-2xl border border-zinc-800 bg-zinc-950 p-6 shadow-2xl text-zinc-100 flex flex-col justify-between">
        {/* Modal Action Bar */}
        <div className="flex items-center justify-between border-b border-zinc-800/80 pb-4 print:hidden">
          <div className="flex items-center gap-2">
            <div className="flex h-8 w-8 items-center justify-center rounded-xl bg-emerald-500/10 border border-emerald-500/20 text-emerald-400">
              <FileText className="h-4 w-4" />
            </div>
            <div>
              <h2 className="text-sm font-bold text-white">
                {isTaxInvoice ? 'Commercial Tax Invoice' : 'Formal Proforma Quotation'}
              </h2>
              <p className="text-[11px] text-zinc-400">
                Official document generated by Agent Sauda B2B Engine
              </p>
            </div>
          </div>

          <div className="flex items-center gap-2">
            <button
              type="button"
              onClick={handlePrint}
              className="inline-flex items-center gap-1.5 rounded-xl bg-indigo-600 hover:bg-indigo-500 px-3.5 py-1.5 text-xs font-semibold text-white shadow-md shadow-indigo-600/20 transition"
            >
              <Printer className="h-3.5 w-3.5" />
              <span>Print / Save PDF</span>
            </button>
            <button
              type="button"
              onClick={onClose}
              className="rounded-xl border border-zinc-800 bg-zinc-900 p-1.5 text-zinc-400 hover:bg-zinc-800 hover:text-white transition"
            >
              <X className="h-4 w-4" />
            </button>
          </div>
        </div>

        {/* Printable Document Sheet */}
        <div className="my-4 rounded-xl border border-zinc-800/80 bg-zinc-900/40 p-6 space-y-6 text-xs print:border-none print:bg-white print:text-black">
          {/* Header & Company Brand */}
          <div className="flex flex-col sm:flex-row sm:items-start justify-between gap-4 border-b border-zinc-800/80 pb-5">
            <div>
              <div className="flex items-center gap-2">
                <span className="text-base font-black tracking-tight text-white print:text-black">
                  {data.merchantName}
                </span>
                <span className="rounded bg-emerald-500/10 border border-emerald-500/20 px-2 py-0.5 text-[10px] font-bold text-emerald-400">
                  GST Verified
                </span>
              </div>
              <p className="text-[11px] text-zinc-400 print:text-zinc-600 mt-1">
                {data.merchantAddress || 'Industrial Area, Phase II, Bengaluru, KA 560068'}
              </p>
              <p className="text-[11px] font-mono text-zinc-400 print:text-zinc-600">
                GSTIN: <strong className="text-zinc-200 print:text-black">{data.merchantGstin || '29AABCU9603R1ZM'}</strong>
              </p>
            </div>

            <div className="text-right sm:text-right space-y-1">
              <div className="text-sm font-black text-indigo-400 uppercase tracking-wide">
                {isTaxInvoice ? 'TAX INVOICE' : 'PROFORMA QUOTE'}
              </div>
              <div className="font-mono text-xs font-bold text-zinc-200 print:text-black">
                #{data.documentNumber}
              </div>
              <div className="text-[11px] text-zinc-400 print:text-zinc-600">
                Date: {data.date}
              </div>
              {data.validUntil && (
                <div className="text-[10px] text-amber-400 flex items-center justify-end gap-1">
                  <Clock className="h-3 w-3" />
                  <span>Valid Until: {data.validUntil}</span>
                </div>
              )}
            </div>
          </div>

          {/* Billed To / Buyer Credentials */}
          <div className="grid grid-cols-1 sm:grid-cols-2 gap-4 rounded-xl bg-zinc-950/60 p-4 border border-zinc-800/60 print:bg-zinc-100">
            <div>
              <span className="text-[10px] font-bold uppercase tracking-wider text-zinc-500 block mb-1">
                Billed To (Customer / Entity)
              </span>
              <div className="font-bold text-zinc-200 print:text-black flex items-center gap-1.5">
                <span>{data.customerName}</span>
                {data.isCustomerVerified && (
                  <span className="inline-flex items-center gap-0.5 text-[10px] font-semibold text-emerald-400 bg-emerald-500/10 px-1.5 py-0.2 rounded">
                    <CheckCircle2 className="h-3 w-3" /> Verified
                  </span>
                )}
              </div>
              {data.customerPhone && (
                <div className="text-[11px] text-zinc-400 print:text-zinc-600 mt-0.5">
                  Phone: {data.customerPhone}
                </div>
              )}
              {data.customerEmail && (
                <div className="text-[11px] text-zinc-400 print:text-zinc-600">
                  Email: {data.customerEmail}
                </div>
              )}
            </div>

            <div className="sm:text-right">
              <span className="text-[10px] font-bold uppercase tracking-wider text-zinc-500 block mb-1">
                Payment & Fulfillment Status
              </span>
              <div className="inline-flex items-center gap-1 rounded-full bg-emerald-500/10 border border-emerald-500/20 px-2.5 py-0.5 text-[11px] font-bold text-emerald-400">
                <ShieldCheck className="h-3 w-3" />
                <span>{data.status}</span>
              </div>
              {data.paymentId && (
                <div className="text-[10px] font-mono text-zinc-400 print:text-zinc-600 mt-1">
                  Gateway Ref: {data.paymentId}
                </div>
              )}
            </div>
          </div>

          {/* Itemized Line Items Table */}
          <div className="overflow-x-auto">
            <table className="w-full text-left border-collapse">
              <thead>
                <tr className="border-b border-zinc-800 text-[11px] font-bold uppercase text-zinc-400 print:text-zinc-700">
                  <th className="py-2.5 pl-2">Item Description</th>
                  <th className="py-2.5 text-center">Qty</th>
                  <th className="py-2.5 text-right">Catalog MRP</th>
                  <th className="py-2.5 text-right">Negotiated Price</th>
                  <th className="py-2.5 pr-2 text-right">Subtotal</th>
                </tr>
              </thead>
              <tbody className="divide-y divide-zinc-800/60 text-xs">
                {data.items.map((item, idx) => {
                  const hasDiscount = item.agreedPrice < item.unitPrice;
                  const itemDiscountPercent = hasDiscount
                    ? Math.round(((item.unitPrice - item.agreedPrice) / item.unitPrice) * 100)
                    : 0;

                  return (
                    <tr key={idx} className="hover:bg-zinc-800/30 print:hover:bg-transparent">
                      <td className="py-2.5 pl-2 font-medium text-zinc-200 print:text-black">
                        {item.productTitle}
                      </td>
                      <td className="py-2.5 text-center text-zinc-300 print:text-black">
                        {item.quantity}
                      </td>
                      <td className="py-2.5 text-right text-zinc-500 line-through">
                        {formatCurrencyAmount(item.unitPrice, currency)}
                      </td>
                      <td className="py-2.5 text-right font-semibold text-emerald-400 print:text-emerald-700">
                        {formatCurrencyAmount(item.agreedPrice, currency)}
                        {hasDiscount && (
                          <span className="ml-1 text-[10px] text-zinc-500 font-normal">
                            (-{itemDiscountPercent}%)
                          </span>
                        )}
                      </td>
                      <td className="py-2.5 pr-2 text-right font-bold text-zinc-100 print:text-black">
                        {formatCurrencyAmount(item.subtotal, currency)}
                      </td>
                    </tr>
                  );
                })}
              </tbody>
            </table>
          </div>

          {/* Tax Breakdown & Total Summary */}
          <div className="grid grid-cols-1 sm:grid-cols-2 gap-6 border-t border-zinc-800/80 pt-4">
            {/* Razorpay UPI QR Code & Authenticity Stamp */}
            <div className="flex items-center gap-4 rounded-xl border border-zinc-800 bg-zinc-950/60 p-3.5 print:bg-zinc-100">
              <div className="h-16 w-16 shrink-0 rounded-lg bg-white p-1 flex items-center justify-center shadow">
                <QrCode className="h-14 w-14 text-slate-900" />
              </div>
              <div className="space-y-1 text-[11px]">
                <span className="font-bold text-zinc-200 print:text-black block">
                  Scan & Pay with Razorpay UPI
                </span>
                <p className="text-[10px] text-zinc-400 print:text-zinc-600">
                  Instant webhook settlement & warehouse inventory reservation.
                </p>
                <div className="text-[9px] font-mono text-zinc-500 truncate max-w-[200px]">
                  Hash: {offerSha256}
                </div>
              </div>
            </div>

            {/* Calculations Table */}
            <div className="space-y-1.5 text-xs text-zinc-400 print:text-zinc-700">
              <div className="flex justify-between">
                <span>Catalog Subtotal</span>
                <span className="text-zinc-200 print:text-black">{formatCurrencyAmount(data.subtotal, currency)}</span>
              </div>

              {data.discountAmount > 0 && (
                <div className="flex justify-between text-emerald-400 print:text-emerald-700 font-medium">
                  <span>AI Negotiated Discount ({data.discountPercent}%)</span>
                  <span>-{formatCurrencyAmount(data.discountAmount, currency)}</span>
                </div>
              )}

              <div className="flex justify-between pt-1 border-t border-zinc-800/60">
                <span>Taxable Amount</span>
                <span>{formatCurrencyAmount(taxableValue, currency)}</span>
              </div>
              <div className="flex justify-between text-[11px]">
                <span>CGST (9.0%)</span>
                <span>{formatCurrencyAmount(cgstAmount, currency)}</span>
              </div>
              <div className="flex justify-between text-[11px]">
                <span>SGST (9.0%)</span>
                <span>{formatCurrencyAmount(sgstAmount, currency)}</span>
              </div>

              <div className="flex justify-between border-t border-zinc-800 pt-2 text-sm font-black text-white print:text-black">
                <span>Total Amount Payable</span>
                <span className="text-emerald-400 print:text-black text-base">
                  {formatCurrencyAmount(data.totalAmount, currency)}
                </span>
              </div>
            </div>
          </div>

          {/* Footer Terms & Cryptographic Integrity */}
          <div className="border-t border-zinc-800/80 pt-3 flex flex-col sm:flex-row sm:items-center justify-between text-[10px] text-zinc-500 print:text-zinc-600">
            <div>
              Generated by <strong>Agent Sauda Autonomous Commerce Protocol</strong>. Standard 30-day return policy applies.
            </div>
            <div className="font-mono mt-1 sm:mt-0 text-emerald-400/80">
              🛡️ Cryptographically Verified Signature
            </div>
          </div>
        </div>

        {/* Bottom Close Button for Modal */}
        <div className="flex justify-end pt-2 print:hidden">
          <button
            type="button"
            onClick={onClose}
            className="rounded-xl border border-zinc-800 bg-zinc-900 px-4 py-2 text-xs font-semibold text-zinc-300 hover:bg-zinc-800 hover:text-white transition"
          >
            Close
          </button>
        </div>
      </div>
    </div>
  );
}
